# Generated by Django 3.0.8 on 2020-08-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_auto_20200806_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codProv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=80)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codLoc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_loc', models.CharField(max_length=80)),
                ('cod_post', models.IntegerField(blank=True, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Provincia')),
            ],
        ),
    ]
