# Generated by Django 3.0.8 on 2020-08-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0003_localidad_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codProve', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('contacto', models.CharField(max_length=60, verbose_name='Nombre del contacto')),
                ('nota_general', models.TextField(verbose_name='nota descriptiva del proveedor')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion de la empresa')),
                ('area_geografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Localidad')),
            ],
        ),
    ]
