# Generated by Django 3.0.8 on 2020-08-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0003_localidad_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('codSecre', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido del secretario')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombrees')),
                ('area_geografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.Localidad')),
            ],
        ),
    ]
